CREATE TABLE IF NOT EXISTS tb_doctor
(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Specialty VARCHAR(30) NOT NULL,
	CPF VARCHAR (11) NOT NULL UNIQUE,
    Salary DECIMAL(8,2) NOT NULL,
	Address VARCHAR(40),
	CEP VARCHAR(8) NOT NULL
);